# Generated by Django 5.1.7 on 2025-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(default='No_number', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
