# Generated by Django 5.1.7 on 2025-03-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_case_case_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.CharField(choices=[('CAIRO_COURT', 'محكمة القاهرة'), ('ALEX_COURT', 'محكمة الإسكندرية'), ('GIZA_COURT', 'محكمة الجيزة'), ('LUXOR_COURT', 'محكمة الأقصر'), ('ASWAN_COURT', 'محكمة أسوان')], default='CAIRO_COURT', max_length=20),
        ),
    ]
