# Generated by Django 5.1.7 on 2025-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('LEGAL', 'شرعي'), ('CRIMINAL', 'جنائي'), ('CIVIL', 'مدني'), ('ADMIN', 'اداري')], default='Legal', max_length=20),
        ),
    ]
