# Generated by Django 6.0.6 on 2026-06-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_hearing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('Interior design', 'Interior design'), ('3d design only', '3d design only'), ('CIVIL', 'CIVIL'), ('ADMIN', 'ADMIN')], default='Legal', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.CharField(choices=[('New cairo', 'New cairo'), ('Zayed', 'Zayed'), ('Nasr city', 'Nasr city'), ('New admin capital', 'New admin capital'), ('ay ebn mtnaka', 'ay ebn mtnaka')], default='CAIRO_COURT', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='lawyer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('OPEN', 'Open'), ('CLOSED', 'CLOSED')], max_length=10),
        ),
    ]
