# Generated by Django 6.0.6 on 2026-06-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_case_case_type_alter_case_court_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.lawyer'),
        ),
    ]
